name: fit_track_pro
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^15.1.2
  flutter_riverpod: ^3.0.3
  freezed_annotation: ^3.1.0
  riverpod_annotation: ^3.0.3
  validators: ^3.0.0
  dynamic_path_url_strategy: ^1.0.0
  flutter_svg: ^2.1.0
  google_fonts: ^6.3.0
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  gap: ^3.0.1

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^3.2.3
  riverpod_generator: ^3.0.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/fit_track_splash.png
    - assets/images/ftp_splash.svg
    - assets/images/fit_splash.png
    - assets/images/login_img.png